### ISSUE TITLE
Count, sort and print (faded example)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#10]
.tsv > .csv

The problem wants you to sort 10 files, we only have 4 - add some note like "if we were to have a larger number of files"

**Comment by torwhite** [comment]
Or maybe change to the 2 files with most words or something

**Comment by kristi-sara** [comment]
changed the tsv > csv. I need to think about that challenge question. Its one of the ones I skipped over for the time being since I couldnt think of what to do at the time.

**Comment by jonjab** [comment]
I think faded example = fill in the blank of a partially completed problem.  I made it more verbose.
