### ISSUE TITLE
Ep. 5 "In Person" grep expressions

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#15]
"In Person" and "in person" grep expressions need to be in quotations. Otherwise all that's being counted is instances of "in" or "In"

ALSO, would be good to add another bash expression showing that the counts are 0 when you search "in person" because it's case sensitive and that's not how the data entry is done. THEN add the -ci flag. it's a weird jump from one to the other without that middle step.

**Comment by kristi-sara** [comment]
canned the in person grep stuff since it was weird. Changed to grep refer
