### ISSUE TITLE
Ep. 5 adding dates to spatial file

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#16]
There should be a couple sentences on what that code is doing for adding data and why we decided to add the date.. I didn't understand why this was being done. after running the code I see it was added to the filename, but I thought it was going to be added to all lines with spatial ???

**Comment by kristi-sara** [comment]
no, its just adding a date to the name of the file since we are piping the results into another file and naming it -------- with date.
