### ISSUE TITLE
Ep. 5 "Extracting data from Desktracker" cut command didn't work

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#19]
Not sure what's going on because I'm not familiar with the command but the windows cut command in the lesson I copied and pasted didn't work in my shell.

**Comment by kristi-sara** [comment]
I forgot to switch out the code. Since our data isn't in fixed columns, it needs a delimiter and the thing that says "macs" underneath is the correct code.
