### ISSUE TITLE
Fix expand text in "Extracting data from Desktracker"

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#30]
Part of the "challenge" text/question is caught up in the solution drop down so it's not visible.

**Comment by ilessing** [comment]
at:  https://ucsbcarpentry.github.io/CustomLibraryBash/05-counting-extracting/index.html#extracting-data-from-desktracker

**Comment by torwhite** [comment]
I'll fix it :) I just didn't have time before the staff meeting and wanted a reminder

**Comment by ilessing** [comment]
Yay @torwhite !
