### ISSUE TITLE
Ep. 5 wc command. Change from .tsv to .csv

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#5]
In the header, we can see the common metadata fields of flight ids: holding_id, official_flight_id, filed_by, etc.

Next, let’s learn about a basic data analysis tool: wc is the “word count” command: it counts the number of lines, words, and bytes. Since we love the wildcard operator, let’s run the command **wc *.tsv** to get counts for all the .csv files in the Desktrackers directory. (it takes a little time to complete):

**Comment by kristi-sara** [comment]
this typo has been fixed
