### ISSUE TITLE
Ep. 5 Indicate using 1(one) vs. l(L) in head command

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/CustomLibraryBash#7]
Add an explanation to text below to use 1 not l, similar to the opposite hint earlier in the lesson. 

"Finally we have our old friend head, that we can use to get the first line of the sorted-lengths.txt:

**$ head -n 1 sorted-lengths.txt**  "

**Comment by kristi-sara** [comment]
I made a change earlier, but revisted it and fixed the wording again. Let me know if you think its still off.
